# Generated by Django 5.0.4 on 2025-06-08 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blockchain', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plugin',
            name='blockchainId',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
