# Generated by Django 5.0.4 on 2025-06-17 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blockchain', '0004_plugin_blockchainid'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='datapacket',
            options={'ordering': ['-queued_dt', '-created']},
        ),
    ]
