# Generated by Django 5.0.4 on 2025-06-17 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blockchain', '0005_alter_datapacket_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='datapacket',
            options={'ordering': ['-updated_on_node', '-created']},
        ),
    ]
