# Generated by Django 5.0.4 on 2025-06-06 22:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('blockchain', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='Block_obj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blockchain.block'),
        ),
    ]
