# Generated by Django 5.0.4 on 2025-06-18 02:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_initial'),
        ('blockchain', '0006_alter_datapacket_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='Block_obj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='blockchain.block'),
        ),
        migrations.AddField(
            model_name='userverification',
            name='Block_obj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='blockchain.block'),
        ),
        migrations.AlterField(
            model_name='user',
            name='UserData_obj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.userdata'),
        ),
        migrations.AlterField(
            model_name='userpubkey',
            name='Block_obj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='blockchain.block'),
        ),
        migrations.AlterField(
            model_name='userverification',
            name='Validator_obj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='blockchain.validator'),
        ),
    ]
