# Generated by Django 5.0.4 on 2025-06-06 22:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blockchain', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('blockchainId', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('id', models.CharField(default='0', max_length=50, primary_key=True, serialize=False)),
                ('modelVersion', models.IntegerField(default=1)),
                ('created', models.DateTimeField(blank=True, null=True)),
                ('last_updated', models.DateTimeField(blank=True, null=True)),
                ('updated_on_node', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('value', models.TextField(default='0')),
                ('User_obj', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created', 'id'],
            },
        ),
        migrations.CreateModel(
            name='UserTransaction',
            fields=[
                ('modelVersion', models.IntegerField(default=1)),
                ('id', models.CharField(default='0', max_length=50, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(blank=True, null=True)),
                ('updated_on_node', models.DateTimeField(auto_now=True, null=True)),
                ('added', models.DateTimeField(auto_now_add=True, null=True)),
                ('publicKey', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('signature', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('validation_error', models.BooleanField(blank=True, default=False, null=True)),
                ('token_value', models.TextField(default='0')),
                ('regarding', models.JSONField(blank=True, default=None, null=True)),
                ('validated', models.BooleanField(blank=True, default=None, null=True)),
                ('enact_dt', models.DateTimeField(blank=True, null=True)),
                ('enacted', models.BooleanField(blank=True, default=None, null=True)),
                ('ReceiverBlock_obj', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sender_block', to='blockchain.block')),
                ('SenderBlock_obj', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receiver_block', to='blockchain.block')),
                ('ReceiverWallet_obj', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='receiver', to='transactions.wallet')),
                ('SenderWallet_obj', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sender', to='transactions.wallet')),
            ],
            options={
                'ordering': ['-created', 'id'],
            },
        ),
    ]
