# Generated by Django 5.0.4 on 2025-06-06 22:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blockchain', '0003_initial'),
        ('legis', '0001_initial'),
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agenda',
            name='Country_obj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_country_obj', to='posts.region'),
        ),
        migrations.AddField(
            model_name='agenda',
            name='Region_obj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_region_obj', to='posts.region'),
        ),
        migrations.AddField(
            model_name='agenda',
            name='Validator_obj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='blockchain.validator'),
        ),
        migrations.AddField(
            model_name='bill',
            name='Block_obj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='blockchain.block'),
        ),
        migrations.AddField(
            model_name='bill',
            name='Country_obj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_country_obj', to='posts.region'),
        ),
        migrations.AddField(
            model_name='bill',
            name='Region_obj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_region_obj', to='posts.region'),
        ),
        migrations.AddField(
            model_name='bill',
            name='Validator_obj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='blockchain.validator'),
        ),
        migrations.AddField(
            model_name='billtext',
            name='Block_obj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='blockchain.block'),
        ),
        migrations.AddField(
            model_name='billtext',
            name='Region_obj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_region_obj', to='posts.region'),
        ),
        migrations.AddField(
            model_name='billtext',
            name='Validator_obj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='blockchain.validator'),
        ),
        migrations.AddField(
            model_name='bill',
            name='BillText_obj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_billtext_obj', to='legis.billtext'),
        ),
        migrations.AddField(
            model_name='committee',
            name='Block_obj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='blockchain.block'),
        ),
        migrations.AddField(
            model_name='committee',
            name='Country_obj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_country_obj', to='posts.region'),
        ),
        migrations.AddField(
            model_name='committee',
            name='Region_obj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_region_obj', to='posts.region'),
        ),
        migrations.AddField(
            model_name='committee',
            name='Validator_obj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='blockchain.validator'),
        ),
        migrations.AddField(
            model_name='district',
            name='Block_obj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='blockchain.block'),
        ),
        migrations.AddField(
            model_name='district',
            name='Country_obj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_country_obj', to='posts.region'),
        ),
        migrations.AddField(
            model_name='district',
            name='ProvState_obj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_provstate_obj', to='posts.region'),
        ),
        migrations.AddField(
            model_name='district',
            name='Region_obj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_region_obj', to='posts.region'),
        ),
        migrations.AddField(
            model_name='district',
            name='Validator_obj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='blockchain.validator'),
        ),
        migrations.AddField(
            model_name='bill',
            name='District_obj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_district_obj', to='legis.district'),
        ),
        migrations.AddField(
            model_name='election',
            name='Block_obj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='blockchain.block'),
        ),
        migrations.AddField(
            model_name='election',
            name='Country_obj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_country_obj', to='posts.region'),
        ),
        migrations.AddField(
            model_name='election',
            name='District_obj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='legis.district'),
        ),
        migrations.AddField(
            model_name='election',
            name='Region_obj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_region_obj', to='posts.region'),
        ),
        migrations.AddField(
            model_name='election',
            name='Validator_obj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='blockchain.validator'),
        ),
        migrations.AddField(
            model_name='government',
            name='Block_obj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='blockchain.block'),
        ),
        migrations.AddField(
            model_name='government',
            name='Country_obj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_country_obj', to='posts.region'),
        ),
        migrations.AddField(
            model_name='government',
            name='Region_obj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_region_obj', to='posts.region'),
        ),
        migrations.AddField(
            model_name='government',
            name='Validator_obj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='blockchain.validator'),
        ),
        migrations.AddField(
            model_name='election',
            name='Government_obj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_government_obj', to='legis.government'),
        ),
        migrations.AddField(
            model_name='committee',
            name='Government_obj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_government_obj', to='legis.government'),
        ),
        migrations.AddField(
            model_name='bill',
            name='Government_obj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_government_obj', to='legis.government'),
        ),
        migrations.AddField(
            model_name='agenda',
            name='Government_obj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_government_obj', to='legis.government'),
        ),
        migrations.AddField(
            model_name='meeting',
            name='Block_obj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='blockchain.block'),
        ),
        migrations.AddField(
            model_name='meeting',
            name='Country_obj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_country_obj', to='posts.region'),
        ),
        migrations.AddField(
            model_name='meeting',
            name='Government_obj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_government_obj', to='legis.government'),
        ),
        migrations.AddField(
            model_name='meeting',
            name='Region_obj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_region_obj', to='posts.region'),
        ),
        migrations.AddField(
            model_name='meeting',
            name='Validator_obj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='blockchain.validator'),
        ),
        migrations.AddField(
            model_name='motion',
            name='Bill_obj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='legis.bill'),
        ),
        migrations.AddField(
            model_name='motion',
            name='Block_obj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='blockchain.block'),
        ),
        migrations.AddField(
            model_name='motion',
            name='Country_obj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_country_obj', to='posts.region'),
        ),
        migrations.AddField(
            model_name='motion',
            name='Government_obj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_government_obj', to='legis.government'),
        ),
        migrations.AddField(
            model_name='motion',
            name='Region_obj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_region_obj', to='posts.region'),
        ),
        migrations.AddField(
            model_name='motion',
            name='Validator_obj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='blockchain.validator'),
        ),
        migrations.AddField(
            model_name='party',
            name='Block_obj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='blockchain.block'),
        ),
        migrations.AddField(
            model_name='party',
            name='Country_obj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_country_obj', to='posts.region'),
        ),
        migrations.AddField(
            model_name='party',
            name='ProvState_obj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_provstate_obj', to='posts.region'),
        ),
        migrations.AddField(
            model_name='party',
            name='Region_obj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_region_obj', to='posts.region'),
        ),
        migrations.AddField(
            model_name='party',
            name='Validator_obj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='blockchain.validator'),
        ),
        migrations.AddField(
            model_name='bill',
            name='Party_obj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='legis.party'),
        ),
        migrations.AddField(
            model_name='person',
            name='Block_obj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='blockchain.block'),
        ),
        migrations.AddField(
            model_name='person',
            name='Country_obj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_country_obj', to='posts.region'),
        ),
        migrations.AddField(
            model_name='person',
            name='Region_obj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_region_obj', to='posts.region'),
        ),
        migrations.AddField(
            model_name='person',
            name='Update_obj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_update_obj', to='posts.update'),
        ),
        migrations.AddField(
            model_name='person',
            name='Validator_obj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='blockchain.validator'),
        ),
        migrations.AddField(
            model_name='motion',
            name='Person_obj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='legis.person'),
        ),
        migrations.AddField(
            model_name='committee',
            name='Chair_obj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='committee_chair', to='legis.person'),
        ),
        migrations.AddField(
            model_name='bill',
            name='Person_obj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='legis.person'),
        ),
        migrations.AddField(
            model_name='statement',
            name='Block_obj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='blockchain.block'),
        ),
        migrations.AddField(
            model_name='statement',
            name='Country_obj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_country_obj', to='posts.region'),
        ),
        migrations.AddField(
            model_name='statement',
            name='District_obj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_district_obj', to='legis.district'),
        ),
        migrations.AddField(
            model_name='statement',
            name='Government_obj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_government_obj', to='legis.government'),
        ),
        migrations.AddField(
            model_name='statement',
            name='Meeting_obj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='debate_key', to='legis.meeting'),
        ),
        migrations.AddField(
            model_name='statement',
            name='Party_obj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='legis.party'),
        ),
        migrations.AddField(
            model_name='statement',
            name='Person_obj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='legis.person'),
        ),
        migrations.AddField(
            model_name='statement',
            name='Region_obj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_region_obj', to='posts.region'),
        ),
        migrations.AddField(
            model_name='statement',
            name='Validator_obj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='blockchain.validator'),
        ),
        migrations.AddField(
            model_name='vote',
            name='Block_obj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='blockchain.block'),
        ),
        migrations.AddField(
            model_name='vote',
            name='Country_obj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_country_obj', to='posts.region'),
        ),
        migrations.AddField(
            model_name='vote',
            name='District_obj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_district_obj', to='legis.district'),
        ),
        migrations.AddField(
            model_name='vote',
            name='Government_obj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_government_obj', to='legis.government'),
        ),
        migrations.AddField(
            model_name='vote',
            name='Motion_obj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='legis.motion'),
        ),
        migrations.AddField(
            model_name='vote',
            name='Party_obj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='legis.party'),
        ),
        migrations.AddField(
            model_name='vote',
            name='Person_obj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='legis.person'),
        ),
        migrations.AddField(
            model_name='vote',
            name='Region_obj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_region_obj', to='posts.region'),
        ),
        migrations.AddField(
            model_name='vote',
            name='Validator_obj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='blockchain.validator'),
        ),
    ]
