"""
Django settings for sovote project.

Generated by 'django-admin startproject' using Django 4.1.2.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""

import os
from pathlib import Path
# import firebase_admin
# from firebase_admin import credentials
# from firebase_admin import initialize_app

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

import importlib

# try:
#     import sys
#     settings_folder = os.path.expanduser('~/Sonet/.data/special')
#     if settings_folder not in sys.path:
#         sys.path.append(settings_folder)
#     from settings import CUSTOM_DEBUG, CUSTOM_SECRET_KEY, PORT, EXTERNAL_IP, LOCAL_IP
# except ModuleNotFoundError:
#     # print('fail58936', ModuleNotFoundError)
#     CUSTOM_SECRET_KEY = ''
#     CUSTOM_DEBUG = 'False'
#     PORT = ''
#     EXTERNAL_IP = ''
#     LOCAL_IP = ''

# try:
#     import sys
#     settings_folder = os.path.expanduser('~/Sonet/.data/special')
#     if settings_folder not in sys.path:
#         sys.path.append(settings_folder)
#     from settings.trusted_origins import ADDRESSES
# except Exception as e:
#     print('trusted_origins fail 4953',str(e))
#     ADDRESSES = []



import os
import sys
import json

# Add '~/myProject/data' to the Python path
sys.path.append(os.path.expanduser("~/Sonet/.data"))
from utils.models import prnt
try:
    from special.settings import CUSTOM_DEBUG, CUSTOM_SECRET_KEY, PORT, EXTERNAL_IP, LOCAL_IP
except ImportError as e:
    # prnt(f"Import error 4953: {e}")
    # print(f"Import error 49532: {e}")
    CUSTOM_SECRET_KEY = ''
    CUSTOM_DEBUG = 'False'
    PORT = ''
    EXTERNAL_IP = ''
    LOCAL_IP = ''

try:
    from special.trusted_sources import ADDRESSES
except ImportError as e:
    ADDRESSES = []


trusted_origins = ['http://www.sovote.center', 'http://sovote.center','http://www.sovote.center:56455', 'http://sovote.center:56455'] + ['https://www.sovote.center', 'https://sovote.center', f'http://127.0.0.1:{PORT}', f"http://{EXTERNAL_IP}:{PORT}",f"https://{EXTERNAL_IP}:{PORT}", f"http://{LOCAL_IP}:{PORT}"]
if ADDRESSES:
    trusted_origins = trusted_origins + ADDRESSES

SECRET_KEY = CUSTOM_SECRET_KEY

DEBUG = CUSTOM_DEBUG if isinstance(CUSTOM_DEBUG, bool) else CUSTOM_DEBUG == 'True'

ALLOWED_HOSTS = ['www.sovote.center', 'sovote.center', '127.0.0.1'] + [EXTERNAL_IP, LOCAL_IP]

CSRF_TRUSTED_ORIGINS = trusted_origins 

CORS_ALLOW_HEADERS = ['*']
CORS_ALLOWED_ORIGINS = trusted_origins

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.humanize',
    'django.contrib.staticfiles',
    'django_user_agents',
    # 'debug_toolbar',
    "django_rq",
    'accounts',
    'blockchain',
    'transactions',
    'posts',
    'utils',
    'legis',
    'geoip2',
    'django_crontab',
    "corsheaders",
    # 'fcm_django',
    'django_social_share',
    # Add the following django-allauth apps
    # 'django.contrib.sites',
    # 'allauth',
    # 'allauth.account',
    # 'allauth.socialaccount',
    # 'allauth.socialaccount.providers.google',
]

AUTH_USER_MODEL = 'accounts.User'

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django_user_agents.middleware.UserAgentMiddleware',
    "corsheaders.middleware.CorsMiddleware",
    'debug_toolbar.middleware.DebugToolbarMiddleware',
]

# If you use django-cors-headers, comment this out:
INSTALLED_APPS.remove('corsheaders')
MIDDLEWARE.remove('corsheaders.middleware.CorsMiddleware')

ROOT_URLCONF = 'sonet.urls'
PROJECT_ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(PROJECT_ROOT, 'Templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'sonet.wsgi.application'


SESSION_COOKIE_AGE = 15811200 # 6 months. "1209600(2 weeks)" by default
SESSION_SAVE_EVERY_REQUEST = True # "False" by default
# If SESSION_SAVE_EVERY_REQUEST is "True", users are logged out if inactive.
# If SESSION_SAVE_EVERY_REQUEST is "False", users are logged out whether active or inactive.

#django toolbar
# INTERNAL_IPS = ('127.0.0.1')


CRONJOBS = [
    ('*/10 * * * *', 'utils.cronjobs.task_runner'),
]

# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }

# https://www.codementor.io/@engineerapart/getting-started-with-postgresql-on-mac-osx-are8jcopb
# must run: sudo service postgresql start
# or try: pg_ctl -D /usr/local/var/postgres start
# or brew services start postgresql
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'so_data',
        'USER': 'queue',
        # 'PASSWORD': 'J0F64WN8P',
        'PASSWORD': 'K9V43S2P1',
        'HOST': '127.0.0.1',
        'PORT': '5432',
    }
}

# from decouple import config
# SECRET_KEY = config('SECRET_KEY', default='your-default-secret-key')
# DEBUG = config('DEBUG', cast=bool, default=False)
# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.postgresql',
#         'NAME': config('DB_NAME', default='so_data'),
#         'USER': config('DB_USER', default='queue'),
#         'PASSWORD': config('DB_PASSWORD', default='K9V43S2P1'),
#         'HOST': config('DB_HOST', default='localhost'),
#         'PORT': config('DB_PORT', default='5432'),
#     }
# }

# LOGGING = {
#     'version': 1,
#     'disable_existing_loggers': False,
#     'handlers': {
#         'console': {
#             'class': 'logging.StreamHandler',
#         },
#     },
#     'root': {
#         'handlers': ['console'],
#         'level': 'DEBUG',
#     },
# }
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "handlers": {
        "console": {
            "level": "INFO",
            "class": "logging.StreamHandler",
        },
        # "file": {
        #     "level": "INFO",
        #     "class": "logging.FileHandler",
        #     "filename": os.path.expanduser("~/SoNodeServer/logs/django_debug.log"),
        # },
    },
    # 'root': {
    #     'handlers': ['console'],
    #     'level': 'DEBUG',
    # },
    "loggers": {
    #     "django": {
    #         "handlers": ["file"],
    #         "level": "INFO",
    #         "propagate": True,
    #     },
        "django": {
            "handlers": ["console"],
            "level": "INFO",
            "propagate": True,
        },
    },
}
# cred = credentials.Certificate(os.path.join(PROJECT_ROOT,  'sovote/sovote-ed703-firebase-adminsdk-xcdqb-8b0028a4f9.json'))
# firebase_admin.initialize_app(cred)
# Optional ONLY IF you have initialized a firebase app already:
# Visit https://firebase.google.com/docs/admin/setup/#python
# for more options for the following:
# Store an environment variable called GOOGLE_APPLICATION_CREDENTIALS
# which is a path that point to a json file with your credentials.
# Additional arguments are available: credentials, options, name
# FIREBASE_APP = initialize_app()
# To learn more, visit the docs here:
# https://cloud.google.com/docs/authentication/getting-started>

# FCM_DJANGO_SETTINGS = {
#      # default: _('FCM Django')
#     "APP_VERBOSE_NAME": "SoVote",
#      # true if you want to have only one active device per registered user at a time
#      # default: False
#     "ONE_DEVICE_PER_USER": False,
#      # devices to which notifications cannot be sent,
#      # are deleted upon receiving error response from FCM
#      # default: False
#     "DELETE_INACTIVE_DEVICES": False,
#     "DEVICE_MODEL": "accounts.CustomFCM",
# }


# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


RQ_QUEUES = {
    'main': {
    'HOST': 'localhost',
    'PORT': 6379,
    'DB': 8,
    'DEFAULT_RESULT_TTL': 3600,  # 1 hour
    },
    'high': {
    'HOST': 'localhost',
    'PORT': 6379,
    'DB': 8,
    'DEFAULT_RESULT_TTL': 3600,
    },
    'low': {
    'HOST': 'localhost',
    'PORT': 6379,
    'DB': 8,
    'DEFAULT_RESULT_TTL': 3600,
    },
}

# AUTHENTICATION_BACKENDS = [
#     'django.contrib.auth.backends.ModelBackend',
#     'allauth.account.auth_backends.AuthenticationBackend'
# ]

# #allAuth
# SITE_ID = 3
# LOGIN_REDIRECT_URL = '/redirect_from_social_auth'
# SOCIALACCOUNT_QUERY_EMAIL = True
# ACCOUNT_LOGOUT_ON_GET= True
# ACCOUNT_UNIQUE_EMAIL = True
# ACCOUNT_EMAIL_REQUIRED = True

# SOCIALACCOUNT_PROVIDERS = {
#     'google': {
#         'SCOPE': [
#             'profile',
#             'email',
#         ],
#         'AUTH_PARAMS': {
#             'access_type': 'online',
#         }
#     }
# }

# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'
# TIME_ZONE = "America/New_York"

USE_I18N = True

USE_TZ = True

GEOIP_PATH = os.path.join(PROJECT_ROOT,  'geoip')


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/

STATIC_URL = 'static/'

STATIC_ROOT = os.path.join(PROJECT_ROOT, 'static_cdn')


# STATICFILES_DIRS = (
#     # os.path.join(PROJECT_ROOT, 'static_cdn'),
#     os.path.join(PROJECT_ROOT, 'static'),
# )


# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

DATA_UPLOAD_MAX_MEMORY_SIZE = 50 * 1024 * 1024  # 50 MB
